export enum ExchangeStatus {
  ARRIVED = 'ITEM_RECEBIDO',
  REJECTED = 'TROCA_RECUSADA',
  DISPATCHED = 'EM_DEVOLUCAO',
  REQUESTED = 'EM_TROCA',
  AUTHORIZED = 'TROCA_AUTORIZADA',
  RECEIVED = 'TROCADO',
}
