export enum SaleStatus {
  OPEN = 'EM_ABERTO',
  CANCELLED = 'CANCELADA',
  PROCESSING = 'EM_PROCESSAMENTO',
  PAID = 'PAGAMENTO_REALIZADO',
  REJECTED = 'REPROVADA',
  IN_TRANSIT = 'EM_TRANSITO',
  DELIVERED = 'ENTREGUE',
  IN_EXCHANGE = 'EM_TROCA',
  EXCHANGED = 'TROCADO',
}
